/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_ikanke_Client */

#ifndef _Included_cn_ikanke_Client
#define _Included_cn_ikanke_Client
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ikanke_Client
 * Method:    init
 * Signature: (Lcn/ikanke/ClientHandler;)V
 */
JNIEXPORT void JNICALL Java_cn_ikanke_Client_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     cn_ikanke_Client
 * Method:    finit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_ikanke_Client_finit
  (JNIEnv *, jobject);

/*
 * Class:     cn_ikanke_Client
 * Method:    Login
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_ikanke_Client_Login
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_ikanke_Client
 * Method:    Logout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_ikanke_Client_Logout
  (JNIEnv *, jobject);

/*
 * Class:     cn_ikanke_Client
 * Method:    SendMessage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_ikanke_Client_SendMessage
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
